added asm
doctor-kaliy/first-term pull request #1
Opened 2020-06-21 16:58 UTC by doctor-kaliy

2020-06-21 18:11 UTC, kt-cpp requested changes

2020-06-21 18:11 UTC, kt-cpp commented on asm/mul.asm
> +mul_long_long:
Можно пожалуйста комментарии с контрактом данной функции

2020-06-21 18:11 UTC, kt-cpp commented on asm/mul.asm
> +add_mul_long_short:
И этой тоже

2020-06-21 22:00 UTC, doctor-kaliy commented on asm/mul.asm
> +mul_long_long:
fixed

2020-06-21 22:00 UTC, doctor-kaliy commented on asm/mul.asm
> +add_mul_long_short:
i eto toje

2020-06-22 10:15 UTC, kt-cpp approved these changes

2020-06-22 10:16 UTC, merged