vector added
doctor-kaliy/first-term pull request #2
Opened 2020-06-22 15:08 UTC by doctor-kaliy

2020-06-22 22:42 UTC, kt-cpp requested changes
В общем, норм.

Можешь поправить что-нибудь/переубедить меня

В следующей итерации замержим

2020-06-22 22:42 UTC, kt-cpp commented on vector/vector.h
> +}
Если уж ставишь ```if```, то можно и без копирования обойтись при его выполнении

Хотя наверное компилятор соптимизирует

2020-06-22 22:42 UTC, kt-cpp commented on vector/vector.h
> +        delete_data();
зачем тут вызов ```delete_data```, если это конструктор

2020-06-22 22:42 UTC, kt-cpp commented on vector/vector.h
> +}
```erase(pos, pos + 1)```

2020-06-22 22:42 UTC, kt-cpp commented on vector/vector.h
> +}
Давай сделаем еще ```assert``` на то, что ```first``` лежит между ```begin()``` и ```last```

И что за мода такая: писать выражения, которые могут быть упрощены? ex: ```(a - b) + b```

2020-06-22 22:42 UTC, kt-cpp commented on vector/vector.h
> +    }
Зачем это?

Почему нельзя просто создать вектор-копию текущего, где ```size === capacity```? Т.е. просто вызвать конструктор

2020-06-22 22:42 UTC, kt-cpp commented on vector/vector.h
> +    vector(vector<T> const&);                  // O(N) strong
зочем

2020-06-23 15:23 UTC, doctor-kaliy commented on vector/vector.h
> +}
На самом деле выражение не упрощается, я не могу написать  например ```last_ = last```, потому что ```last``` это ```const_iterator```. Зато, ```begin()``` не константный, поэтому таким образом снимается константность. Ну не делать же ```const_cast```. Энивэй, я поменял, ещё вместо цикла написал ```move```, который вроде неплохо тут смотрится.

2020-06-23 20:47 UTC, kt-cpp requested changes
Я много написал, но главное, что надо исправить помечено "Серьёзно." жирным шрифтом

2020-06-23 20:47 UTC, kt-cpp commented on vector/vector.h
> +    void copy_all(T*, T const*, size_t);
Возможно, я что-то не заметил, но copy_all и destroy_all не имеют никакого отношения к классу. Это хорошо обозначить, отметив их, например, просто friend

2020-06-23 20:47 UTC, kt-cpp commented on vector/vector.h
> +        T* new_data = static_cast<T*>(operator new(other.size_ * sizeof(T)));
В общем случае, не рекомендуется использовать просто выделенный кусок памяти для неинициализированного типизированного хранилища, так как он может не отвечать требованиям alighment'а типа T. Для этого есть std::aligned_storage<T>.

2020-06-23 20:47 UTC, kt-cpp commented on vector/vector.h
> +        T* new_data = static_cast<T*>(operator new(other.size_ * sizeof(T)));
Что ещё в нём хорошо, это RAII, что позволяет избежать неуклюжих `catch (...)`. (вообще забить на исключения, переложив работу на деструкторы)

2020-06-23 20:47 UTC, kt-cpp commented on vector/vector.h
> +    std::swap(capacity_, other.capacity_);
В данном случае неважно, но в примениии copy-and-swap идиомы принято писать так:
```
using std::swap;
swap(field1, other.field1);
swap(field2, other.field2);
…
swap(fieldn, other.fieldn);
```

Это позволяет привнести в область видимости swap'ы для каких-нибудь классов, которые не реализованы через std::swap. (см. ADT он же Koenig lookup)

2020-06-23 20:47 UTC, kt-cpp commented on vector/vector.h
> +    return *(data_ + i);
Не суть важно, но почему не data_[i]? Кажется, что лучше выражает намерение

2020-06-23 20:47 UTC, kt-cpp commented on vector/vector.h
> +        tmp.new_buffer(new_capacity);
**Серьёзно.** Ты сначала копируешь все элементы из `*this` в новый вектор, потому удаляешь их, а потом снова копируешь их из *this? Звучит не очень эффективно

2020-06-23 20:47 UTC, kt-cpp commented on vector/vector.h
> +    T* ptr = static_cast<T*>(operator new(new_capacity * sizeof(T)));
Казалось бы, логично обновлять capacity в этой функции

2020-06-23 20:47 UTC, kt-cpp commented on vector/vector.h
> +    } catch (...) {
Уже говорил про aligned_storage. (а ещё unitialized_copy/uninitialized_move и std)

2020-06-23 20:47 UTC, kt-cpp commented on vector/vector.h
> +    tmp.reserve(capacity_? capacity_ * 2 : 1);
Вспоминаем, что reserve делает уже 3 прохода по данным, и в итоге получается уже 4

2020-06-23 23:25 UTC, doctor-kaliy commented on vector/vector.h
> +    void copy_all(T*, T const*, size_t);
Сделал ```static```, вроде тоже норм.

2020-06-23 23:25 UTC, doctor-kaliy commented on vector/vector.h
> +        T* new_data = static_cast<T*>(operator new(other.size_ * sizeof(T)));
Сорокин так писал и хотел что бы мы ручками половили это дело(домашка вроде как на исключения и гарантии), но спасибо, ознакомлюсь. Остальные недочёты вроде поправил.

2020-06-24 10:40 UTC, kt-cpp approved these changes

2020-06-24 10:40 UTC, kt-cpp commented on vector/vector.h
> +    reserve(capacity_? capacity_ * 2 : 1);
Лучше использовать понятные условия на интегральных типах данных, а не приводить их к булевым

2020-06-24 10:40 UTC, kt-cpp commented on vector/vector.h
> +    if (other.capacity_ != 0) {
Наверное ты хотел `other.size_`

2020-06-24 10:40 UTC, kt-cpp commented on vector/vector.h
> +    assert(i < size_);
Не знаю писали про ассёрты или нет, но лучше в публичных методах их не иметь, по крайней мере в релизной сборке

2020-06-24 10:40 UTC, kt-cpp commented on vector/vector.h
> +T* vector<T>::new_buffer(size_t size) const {
В целом контракт и логика этой функции странные. Не очень понятно зачем ей привязка к классу, а не быть статической принимая больше параметров, раз как писалось до этого, она не меняет `capacity_`

2020-06-24 12:32 UTC, doctor-kaliy commented
Тесты пофиксил. Го мёрджить.

2020-06-24 12:44 UTC, kt-cpp commented on vector/vector.h
> +    if (other.capacity_ != 0) {
Пофиесил

2020-06-24 12:44 UTC, merged