added bigint
doctor-kaliy/first-term pull request #3
Opened 2020-07-01 02:39 UTC by doctor-kaliy

2020-07-02 20:49 UTC, kt-cpp requested changes

2020-07-02 20:49 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        data.push_back(signum * static_cast<uint32_t>(a));
в случае отрицательного числа ты кастанешь его к беззнаковому, потом домножишь на -1 а потом снова в беззнаковое

2020-07-02 20:49 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    this->sign = sign;
почему сигн не в инит листе?

2020-07-02 20:49 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    sign = 0;
список инициализации

2020-07-02 20:49 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    sign = other.sign;
тоже

2020-07-02 20:49 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    int32_t signum = 0;
сразу sign = 0, в ифе = 1

2020-07-02 20:49 UTC, kt-cpp commented on bigint/big_integer.cpp
> +            if (str[ptr] < '0' || str[ptr] > '9') {
isdigit

2020-07-02 20:49 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    if (ptr == len) {
то есть строка "-" это 0?

2020-07-02 20:49 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        size_t begin, size_t end, std::function<uint64_t(uint32_t, uint32_t)> const& op) {
using на тип std::function

2020-07-02 20:49 UTC, kt-cpp commented on bigint/big_integer.cpp
> +            sign = sign == cmp? 1 : -1;
скобки

2020-07-02 20:49 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        a[a.size() - i - 1] = (swc & UINT32_MAX);
(swc & UINT32_MAX) в метод + статик каст

2020-07-02 20:49 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    if (a.size() - st < prefix) {
a.size() < st не бывает?

2020-07-02 20:49 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    uint32_t f = ((static_cast<uint64_t>(UINT32_MAX) + 1)
static_cast<uint64_t>(UINT32_MAX) в константы

2020-07-02 20:49 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        __uint128_t x = (static_cast<__uint128_t>(get_word(this_abs, this_abs.size() - 1 - j)) << 64U) +
ААААА самому не больно?

2020-07-02 20:49 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        for (unsigned int & i : value) {
int ...

2020-07-02 20:49 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    data[0] = shifted >> 32ULL;
достойно метода со статик кастом

2020-07-02 20:49 UTC, kt-cpp commented on bigint/big_integer.h
> +    data_storage data;
public data ?

2020-07-02 20:49 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        int32_t sign = a.sign;
зачем это отдельная переменная

2020-07-03 16:57 UTC, doctor-kaliy commented on bigint/big_integer.cpp
> +        data.push_back(signum * static_cast<uint32_t>(a));
Я не понял о чем это, но что-то сделал.

2020-07-03 16:57 UTC, doctor-kaliy commented on bigint/big_integer.cpp
> +    this->sign = sign;
починил

2020-07-03 16:57 UTC, doctor-kaliy commented on bigint/big_integer.cpp
> +    sign = 0;
починил

2020-07-03 16:58 UTC, doctor-kaliy commented on bigint/big_integer.cpp
> +    sign = other.sign;
тоже

2020-07-03 16:58 UTC, doctor-kaliy commented on bigint/big_integer.cpp
> +    int32_t signum = 0;
фиксед

2020-07-03 16:58 UTC, doctor-kaliy commented on bigint/big_integer.cpp
> +            if (str[ptr] < '0' || str[ptr] > '9') {
сделал

2020-07-03 16:58 UTC, doctor-kaliy commented on bigint/big_integer.cpp
> +    if (ptr == len) {
вроде исправил

2020-07-03 16:58 UTC, doctor-kaliy commented on bigint/big_integer.cpp
> +        size_t begin, size_t end, std::function<uint64_t(uint32_t, uint32_t)> const& op) {
сделал, но поясни зачем, пожалуйста.

2020-07-03 16:59 UTC, doctor-kaliy commented on bigint/big_integer.cpp
> +            sign = sign == cmp? 1 : -1;
не понял, поставил какие-то скобки

2020-07-03 16:59 UTC, doctor-kaliy commented on bigint/big_integer.cpp
> +        a[a.size() - i - 1] = (swc & UINT32_MAX);
в метод вынес. что значит "+ статик каст"?

2020-07-03 16:59 UTC, doctor-kaliy commented on bigint/big_integer.cpp
> +    if (a.size() - st < prefix) {
не бывает очев

2020-07-03 16:59 UTC, doctor-kaliy commented on bigint/big_integer.cpp
> +    uint32_t f = ((static_cast<uint64_t>(UINT32_MAX) + 1)
fixed

2020-07-03 17:00 UTC, doctor-kaliy commented on bigint/big_integer.cpp
> +        __uint128_t x = (static_cast<__uint128_t>(get_word(this_abs, this_abs.size() - 1 - j)) << 64U) +
хз как исправить, сделал метод get_word128

2020-07-03 17:00 UTC, doctor-kaliy commented on bigint/big_integer.cpp
> +        for (unsigned int & i : value) {
lol, popravil

2020-07-03 17:00 UTC, doctor-kaliy commented on bigint/big_integer.cpp
> +    data[0] = shifted >> 32ULL;
объясните популярнее, пожалуйста. метод сделал

2020-07-03 17:00 UTC, doctor-kaliy commented on bigint/big_integer.h
> +    data_storage data;
исправлено

2020-07-03 17:01 UTC, doctor-kaliy commented on bigint/big_integer.cpp
> +        int32_t sign = a.sign;
исправил

2020-07-04 18:32 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        data.push_back(signum * static_cast<uint32_t>(a));
А сделал ты неоч. Зачем ты беззнаковое умножаешь на -1? А в новой версии - зачем кастуешь к 64?

2020-07-04 18:33 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    int32_t signum = 0;
Предлагалось вынести sign в список инциализации, ты сделал не то

2020-07-04 18:36 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        size_t begin, size_t end, std::function<uint64_t(uint32_t, uint32_t)> const& op) {
Для читабельности

2020-07-04 18:38 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        a[a.size() - i - 1] = (swc & UINT32_MAX);
прикастуй аргументы, чтобы типы правильно выводились как у аргументов &, так и у возвращаемого значения (сейчас это делается неявно)

2020-07-04 18:38 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        a[a.size() - i - 1] = (swc & UINT32_MAX);
подсказка: сначала макс к 64, потом &,  потом результат к 32

2020-07-04 18:40 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        a[a.size() - i - 1] = (swc & UINT32_MAX);
кстати у тебя есть кастнутая константа

2020-07-04 18:41 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        __uint128_t x = (static_cast<__uint128_t>(get_word(this_abs, this_abs.size() - 1 - j)) << 64U) +
все еще плохо читается, разложи что-то по более менее явным действиям

2020-07-04 18:43 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    data[0] = shifted >> 32ULL;
конструкция часто повторяется, засоряет код

2020-07-04 18:48 UTC, kt-cpp requested changes
Оставил по старым + новый маленький

2020-07-04 18:48 UTC, kt-cpp commented on bigint/big_integer.h
> +    using function = std::function<T(uint32_t, uint32_t)>;
[design] конфликт имен

2020-07-05 21:08 UTC, doctor-kaliy commented on bigint/big_integer.cpp
> +        data.push_back(signum * static_cast<uint32_t>(a));
В новой версии использую ```std::abs```. Кастую в 64, потому что```std::abs(INT_MIN)``` не представим в инте. На cppreference сказано, что это UB. Раньше кастовал к беззнаковому и умножал на -1 вместо ```~a + 1```.  Дай подсказку если можно лучше, я не умею.

2020-07-05 21:09 UTC, doctor-kaliy commented on bigint/big_integer.cpp
> +    int32_t signum = 0;
вынес

2020-07-05 21:09 UTC, doctor-kaliy commented on bigint/big_integer.cpp
> +        a[a.size() - i - 1] = (swc & UINT32_MAX);
сделал

2020-07-05 21:10 UTC, doctor-kaliy commented on bigint/big_integer.cpp
> +    if (a.size() - st < prefix) {
Почему не зарезолвлено? Разве бывает?

2020-07-05 21:10 UTC, doctor-kaliy commented on bigint/big_integer.cpp
> +        __uint128_t x = (static_cast<__uint128_t>(get_word(this_abs, this_abs.size() - 1 - j)) << 64U) +
Это было в более старой версии,  В новой появился ```build128```.

2020-07-05 21:11 UTC, doctor-kaliy commented on bigint/big_integer.h
> +    using function = std::function<T(uint32_t, uint32_t)>;
Поменял имя. Но не оч понял про конфликт. Можно подробнее?

2020-07-06 13:42 UTC, doctor-kaliy commented on bigint/big_integer.cpp
> +        data.push_back(signum * static_cast<uint32_t>(a));
В новой версии просто заифал INT_MIN

2020-07-06 17:50 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    if (n >= val.size()) {
тернарник бы подошел

2020-07-06 17:50 UTC, kt-cpp commented on bigint/big_integer.h
> +    using function = std::function<T(uint32_t, uint32_t)>;
ты вроде исправил, но все равно: пользоваться вещами с одинаковым названием из разных неймспейсов опасно, человек, который будет поддерживать твой код может не заметить

2020-07-06 17:53 UTC, kt-cpp approved these changes
нормально

2020-07-06 17:53 UTC, merged